### ISSUE TITLE
Probably needs more mappings for Vulkan

### ISSUE THREAD

**Issue by RAOF** [canonical/mesa-core20#14]
`graphics-core20` probably doesn't need to ship libvulkan (that's platform agnostic), but it *does* need to ship the relevant ICD and put the `$ICD.json` file wherever libvulkan will look for it.

(Just a super quick bug for now so that I don't forget all about it)

**Comment by Saviq** [comment]
Done in [MirServer/mesa-core22](https://github.com/MirServer/mesa-core22)
